name: 'DKAN Demo'
prodUrl: http://catalog-demo.interra.io
testUrl: http://catalog-demo.interra.io
devUrl: 'http://admin.d8.dkandemo.nuamsdev.com'
#publicPath: '/interra/'
identifier: dkan-demo
schema: pod-full
description: 'this is a demo'
front-page-icon-collection: theme
front-page-icons:
 - cityplanning
 - financeandbudgeting
 - healthcare
 - transportation
search:
  type: simpleSearch
  fields:
    - title
    - keyword
    - publisher
    - description
    - theme
    - modified
    - distribution
siteMap:
- title: Home
  loc: "/"
  children:
  - title: About
    loc: "/about"
  - title: Search
    loc: "/search"
  - title: API
    loc: "/api"
  - title: Groups
    loc: "/groups"
    children:
    - collections
siteMapCollections:
  - organization
  - dataset
  - distribution
fontConfig:
  backColor: "#f9fafb"
  navBarBackColor: "#205493"
  navBarLink: "#FFFFFF"
  navBarLinkActive: "#FFFFFF"
  navBarLinkHoverBack: "#112E51"
  navBarLinkActiveBack: "#112E51"
  navBarLinkActiveHoverBack: "#f2d13c"
  navBarLinkActiveHover: "#FFFFFF"
  link: "#0071BC"
  linkHover: "#205493"
  linkFocus: "#205493"
  heroBackColor:   "#0071BC"
  heroImageUrl:    "icon-pattern-bg.svg"
  footerBackColor: "#323A45"
  footerFontColor: "#FFFFFF"
  footerLinkColor: "#FFFFFF"

